# Generated by Django 2.0 on 2017-12-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20171223_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, max_length=600)),
                ('university', models.TextField(max_length=40)),
                ('teacher', models.TextField(max_length=40)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
